export type CaptureLifecycle = 'idle'|'starting'|'capturing'|'paused'|'processing'|'review'|'attested'|'discarded'|'expired'|'invalidated'|'failed';
export interface CaptureBinding { sessionId:string; roundId:string; patientId:string; physicianId:string; deviceId:string; patientSnapshotId:string; startedAt:string; expiresAt:string; }
export interface EncryptedAudioChunk { readonly ciphertext:Uint8Array; readonly iv:Uint8Array; }
export interface CaptureState { lifecycle:CaptureLifecycle; binding?:CaptureBinding; reason?:string; bufferedBytes:number; }
export interface CaptureControllerOptions { maxBufferBytes?:number; timeoutMs?:number; now?:()=>Date; onStateChange?:(state:CaptureState)=>void; }
const TERMINAL = new Set<CaptureLifecycle>(['attested','discarded','expired','invalidated','failed']);
export class CaptureController {
 private state:CaptureState={lifecycle:'idle',bufferedBytes:0}; private readonly options:{maxBufferBytes:number;timeoutMs:number;now:()=>Date;onStateChange?: (state:CaptureState)=>void}; private key?:CryptoKey; private chunks:EncryptedAudioChunk[]=[]; private timeout?:ReturnType<typeof setTimeout>; private generation=0; private reservedBytes=0;
 constructor(options:CaptureControllerOptions={}){this.options={maxBufferBytes:options.maxBufferBytes??2*1024*1024,timeoutMs:options.timeoutMs??300000,now:options.now??(()=>new Date()),onStateChange:options.onStateChange};}
 getState():CaptureState{return {...this.state,binding:this.state.binding&&{...this.state.binding}};} subscribe(listener:(state:CaptureState)=>void):()=>void{const previous=this.options.onStateChange;this.options.onStateChange=s=>{previous?.(s);listener(s);};return()=>{this.options.onStateChange=previous;};} isTerminal(){return TERMINAL.has(this.state.lifecycle);} getEncryptedBuffer(){return this.chunks.slice();}
 async start(binding:CaptureBinding):Promise<void>{if(this.state.lifecycle!=='idle')throw new Error('Capture session is already active or terminal');if(!binding.patientId||!binding.sessionId||!binding.roundId||!binding.physicianId||!binding.deviceId||!binding.patientSnapshotId)throw new Error('Capture requires a complete patient and session binding');const expiry=Date.parse(binding.expiresAt),started=Date.parse(binding.startedAt),now=this.options.now().getTime();if(!Number.isFinite(expiry)||!Number.isFinite(started)||expiry<=now||started>now||expiry<=started)throw new Error('Capture binding timestamps are invalid or expired');this.state={lifecycle:'starting',binding:{...binding},bufferedBytes:0};this.emit();const generation=++this.generation;try{this.key=await crypto.subtle.generateKey({name:'AES-GCM',length:256},true,['encrypt','decrypt']);}catch(error){this.fail('Unable to initialize encrypted capture');throw error;}if(generation!==this.generation||this.state.lifecycle!=='starting'){this.key=undefined;throw new Error('Capture start was cancelled');}if(this.options.now().getTime()>=expiry){this.expire('Capture binding expired while starting');throw new Error('Capture binding expired while starting');}this.state={lifecycle:'capturing',binding:{...binding},bufferedBytes:0};this.timeout=setTimeout(()=>this.expire('Capture timed out'),Math.min(this.options.timeoutMs,expiry-this.options.now().getTime()));this.emit();}
 pause(reason='Paused by physician'){this.require('capturing');this.state={...this.state,lifecycle:'paused',reason};this.emit();} resume(){this.require('paused');this.state={...this.state,lifecycle:'capturing',reason:undefined};this.emit();}
 interrupt(reason='Capture interrupted'){if(!this.isTerminal()&&this.state.lifecycle!=='idle')this.invalidate(reason);} handleInterruption(reason='Capture interrupted'){this.interrupt(reason);} handleOffline(){this.interrupt('Connectivity lost; encrypted reconnect buffer discarded');}
 invalidateIfPatientChanged(id:string){if(this.state.binding&&this.state.binding.patientId!==id)this.invalidate('Patient changed; capture invalidated');} invalidateIfBindingChanged(b:Pick<CaptureBinding,'patientId'|'sessionId'|'roundId'|'physicianId'|'deviceId'|'patientSnapshotId'>){const c=this.state.binding;if(c&&(c.patientId!==b.patientId||c.sessionId!==b.sessionId||c.roundId!==b.roundId||c.physicianId!==b.physicianId||c.deviceId!==b.deviceId||c.patientSnapshotId!==b.patientSnapshotId))this.invalidate('Capture context changed; session invalidated');}
 stop():CaptureState{if(this.state.lifecycle!=='capturing'&&this.state.lifecycle!=='paused')return this.getState();this.clearTimeout();this.state={...this.state,lifecycle:'processing'};this.emit();if(this.state.lifecycle!=='processing')return this.getState();this.state={...this.state,lifecycle:'review'};this.emit();return this.getState();} attest(){if(this.state.lifecycle!=='review')throw new Error('Only a stopped review can be attested');this.terminal('attested','Attested; ephemeral capture erased');} discard(reason='Discarded by physician'){if(this.state.lifecycle!=='idle')this.terminal('discarded',reason);} expire(reason='Capture expired'){if(!this.isTerminal())this.terminal('expired',reason);} invalidate(reason='Capture invalidated'){if(!this.isTerminal())this.terminal('invalidated',reason);} fail(reason='Capture failed'){if(!this.isTerminal())this.terminal('failed',reason);} recoverAfterCrash(){if(this.state.lifecycle!=='idle')this.terminal('discarded','Capture discarded after crash recovery');}
 async appendAudio(data:Blob|ArrayBuffer|Uint8Array):Promise<boolean>{this.require('capturing');const bytes=data instanceof Blob?new Uint8Array(await data.arrayBuffer()):data instanceof Uint8Array?data:new Uint8Array(data);const allocation=bytes.byteLength+28;if(this.state.bufferedBytes+this.reservedBytes+allocation>this.options.maxBufferBytes){this.fail('Encrypted reconnect buffer limit reached');return false;}this.reservedBytes+=allocation;try{if(!this.key){this.fail('Ephemeral encryption key unavailable');return false;}const generation=this.generation,key=this.key,iv=crypto.getRandomValues(new Uint8Array(12)),ciphertext=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,bytes as unknown as BufferSource));if(generation!==this.generation||this.state.lifecycle!=='capturing'||this.key!==key||!this.state.binding||this.options.now().getTime()>=Date.parse(this.state.binding.expiresAt)){ciphertext.fill(0);iv.fill(0);if(this.state.lifecycle==='capturing')this.expire('Capture expired before encrypted audio commit');return false;}this.chunks.push({ciphertext,iv});this.state={...this.state,bufferedBytes:this.state.bufferedBytes+allocation};this.emit();return true;}catch(error){this.fail('Encrypted capture failed');throw error;}finally{this.reservedBytes=Math.max(0,this.reservedBytes-allocation);}}
 private terminal(l:Extract<CaptureLifecycle,'attested'|'discarded'|'expired'|'invalidated'|'failed'>,reason:string){this.clearTimeout();this.generation++;this.erase();this.state={lifecycle:l,reason,bufferedBytes:0};this.emit();} private erase(){this.chunks.forEach(c=>{c.ciphertext.fill(0);c.iv.fill(0);});this.chunks=[];this.reservedBytes=0;this.key=undefined;} private clearTimeout(){if(this.timeout)clearTimeout(this.timeout);this.timeout=undefined;} private require(l:CaptureLifecycle){if(this.state.lifecycle!==l)throw new Error(`Capture must be ${l}`);} private emit(){try{this.options.onStateChange?.(this.getState());}catch{ /* observers cannot compromise capture lifecycle */ }}
}
export const createCaptureController=(options?:CaptureControllerOptions)=>new CaptureController(options);
