export type TranscriptSpeaker = "physician" | "resident" | "fellow" | "nurse" | "other" | "unknown";
export interface TranscriptBinding { sessionId:string; roundId:string; patientId:string; physicianId:string; deviceId:string; patientSnapshotId:string; startedAt:string; expiresAt:string; source:"rounds-audio"; ownershipToken?:string; captureNonce?:string; }
export interface AttributedTranscriptSegment { id:string; binding:Omit<TranscriptBinding,"ownershipToken"|"captureNonce">; speaker:TranscriptSpeaker; text:string; startMs:number; endMs:number; uncertainty:number; expiresAt:string; }
export interface ProviderSegment { text?:unknown; start?:unknown; end?:unknown; speaker?:unknown; avg_logprob?:unknown; no_speech_prob?:unknown; }
export interface TranscriptProvider { (audio:Uint8Array,mime:string,signal:AbortSignal):Promise<unknown>; }
export type TranscriptProcessFailure="expired"|"cancelled"|"unsupported"|"provider-error";
export class TranscriptProcessingError extends Error { readonly code:TranscriptProcessFailure; constructor(code:TranscriptProcessFailure,message:string=code){super(message);this.name="TranscriptProcessingError";this.code=code;} }
export const ALLOWED_AUDIO_MIME_TYPES=new Set(["audio/webm","audio/wav","audio/wave","audio/x-wav","audio/mp4","audio/mpeg","audio/ogg"]);
export function disposeTemporaryTranscript(segments:AttributedTranscriptSegment[]):void{for(const s of segments)s.text="";segments.splice(0,segments.length);}
export function isTemporaryTranscriptExpired(s:AttributedTranscriptSegment[],now=Date.now()):boolean{return s.length>0&&Date.parse(s[0].expiresAt)<=now;}
export function isBindingUsable(b:TranscriptBinding,now=Date.now()):boolean{const a=[b.sessionId,b.roundId,b.patientId,b.physicianId,b.deviceId,b.patientSnapshotId,b.startedAt,b.expiresAt];return b.source==="rounds-audio"&&a.every(v=>typeof v==="string"&&v.trim()!=="")&&Date.parse(b.startedAt)<=now&&Date.parse(b.expiresAt)>now;}
function segments(v:unknown):unknown[]|null{return Array.isArray(v)?v:v&&typeof v==="object"&&Array.isArray((v as {segments?:unknown}).segments)?(v as {segments:unknown[]}).segments:null;}
export async function processTemporaryTranscript(audio:Uint8Array,binding:TranscriptBinding,provider:TranscriptProvider,o:{mimeType?:string;signal?:AbortSignal;now?:()=>number;maxAttempts?:number;retryDelayMs?:number;delay?: (ms:number|undefined,signal:AbortSignal)=>Promise<void>}={}):Promise<AttributedTranscriptSegment[]>{const now=o.now??Date.now,mime=o.mimeType??"audio/webm";if(!audio.byteLength||!ALLOWED_AUDIO_MIME_TYPES.has(mime))throw new TranscriptProcessingError("unsupported");if(!isBindingUsable(binding,now()))throw new TranscriptProcessingError("expired");const signal=o.signal??new AbortController().signal;let out:unknown,err:unknown;const attempts=Math.min(3,Math.max(1,o.maxAttempts??2));for(let i=0;i<attempts;i++){if(signal.aborted)throw new TranscriptProcessingError("cancelled");if(Date.parse(binding.expiresAt)<=now())throw new TranscriptProcessingError("expired");try{out=await provider(audio,mime,signal);break}catch(e){err=e;if(i+1<attempts&&o.retryDelayMs){await(o.delay??((ms:number|undefined)=>new Promise<void>(r=>setTimeout(r,ms))))(o.retryDelayMs,signal);}}}if(signal.aborted)throw new TranscriptProcessingError("cancelled");if(Date.parse(binding.expiresAt)<=now())throw new TranscriptProcessingError("expired");const raw=segments(out);if(!raw)throw new TranscriptProcessingError("provider-error");let prev=0;const safe:{sessionId:string;roundId:string;patientId:string;physicianId:string;deviceId:string;patientSnapshotId:string;startedAt:string;expiresAt:string;source:"rounds-audio"}={sessionId:binding.sessionId,roundId:binding.roundId,patientId:binding.patientId,physicianId:binding.physicianId,deviceId:binding.deviceId,patientSnapshotId:binding.patientSnapshotId,startedAt:binding.startedAt,expiresAt:binding.expiresAt,source:"rounds-audio"};const result:AttributedTranscriptSegment[]=[];for(let i=0;i<raw.length;i++){const x=raw[i] as ProviderSegment;if(!x||typeof x.text!=="string"||typeof x.start!=="number"||typeof x.end!=="number"||!Number.isFinite(x.start)||!Number.isFinite(x.end)||x.start<0||x.end<=x.start||x.start*1000<prev||typeof x.speaker!=="string"||!["physician","resident","fellow","nurse","other","unknown"].includes(x.speaker)||(x.no_speech_prob!==undefined&&(typeof x.no_speech_prob!=="number"||x.no_speech_prob<0||x.no_speech_prob>1)))throw new TranscriptProcessingError("provider-error");const start=x.start*1000,end=x.end*1000;result.push({id:`${binding.sessionId}:${i}`,binding:safe,speaker:x.speaker as TranscriptSpeaker,text:x.text.trim(),startMs:start,endMs:end,uncertainty:typeof x.no_speech_prob==="number"?x.no_speech_prob:0.5,expiresAt:binding.expiresAt});prev=end;}return result;}
