import assert from "node:assert/strict";
import test from "node:test";
import { canDurablyWrite, durableWriteViolations, hasValidSupportingSpan, isAllowedDurableMaterial, isBindingMatch } from "../decisionScribePolicy";
import type { Attestation, CaptureBinding, DecisionCandidate, DecisionDraft } from "../../../types/decisionScribe";

const binding: CaptureBinding = { sessionId: "session-1" as never, roundId: "round-1", patientId: "SYNTH-A", physicianId: "physician-1", deviceId: "device-1", patientSnapshotId: "snapshot-1", patientSnapshotCapturedAt: "2026-01-01T00:00:00Z", source: "rounds-audio", startedAt: "2026-01-01T00:00:00Z", expiresAt: "2099-01-01T00:00:00Z" };
const attestation: Attestation = { id: "attest-1" as never, draftId: "draft-1" as never, sessionId: binding.sessionId, patientId: binding.patientId, physicianId: binding.physicianId, roundId: binding.roundId, deviceId: binding.deviceId, attestedAt: "2026-01-01T00:01:00Z", approvedCandidateIds: ["candidate-1" as never] };
const candidate = (overrides: Partial<DecisionCandidate> = {}): DecisionCandidate => ({ id: "candidate-1" as never, binding, speaker: "physician", statementType: "decision", polarity: "affirmed", destination: "clinicalSummary", proposedContent: "Continue plan", confidence: 0.9, supportingSpan: { segmentId: "segment-1" as never, startMs: 10, endMs: 40, text: "Continue plan", speaker: "physician", sessionId: binding.sessionId, patientId: binding.patientId }, disposition: "approved", source: "rounds-audio", provenance: "spoken-span", material: "provisional-structured", ...overrides });
const request = (value: Partial<DecisionCandidate> = {}, extra: Partial<{ attestation: Attestation; material: "approved-structured"; currentPatientSnapshotId: string; draft: DecisionDraft }> = {}) => { const item = candidate(value); const draft: DecisionDraft = { id: "draft-1" as never, binding, candidates: [item], createdAt: binding.startedAt, expiresAt: binding.expiresAt, provenance: "provisional", status: "review" }; return { candidate: item, binding, attestation, draft, material: "approved-structured" as const, now: new Date("2026-01-01T00:05:00Z"), ...extra }; };

test("accepts fully bound, evidenced, affirmed, attested candidate", () => { assert.equal(canDurablyWrite(request()), true); assert.equal(isBindingMatch(candidate(), binding), true); });
test("rejects unsafe disposition and polarity", () => { for (const disposition of ["pending", "rejected"] as const) assert.ok(durableWriteViolations(request({ disposition })).includes(disposition === "pending" ? "pending" : "rejected")); for (const polarity of ["proposed", "uncertain", "negated"] as const) assert.ok(durableWriteViolations(request({ polarity })).includes(polarity === "uncertain" ? "uncertain" : "unsupported")); });
test("rejects malformed, expired, forged, stale, or impermissible inputs", () => { assert.ok(durableWriteViolations(request({ supportingSpan: undefined as never })).includes("missing-span")); assert.ok(durableWriteViolations(request({ supportingSpan: { ...candidate().supportingSpan, sessionId: "other" as never } })).includes("invalid-span")); assert.ok(durableWriteViolations(request({ binding: { ...binding, source: "live-ehr" as never } })).includes("invalid-provenance")); assert.ok(durableWriteViolations(request({ binding: { ...binding, expiresAt: "2020-01-01T00:00:00Z" } })).includes("expired")); assert.ok(durableWriteViolations(request({}, { currentPatientSnapshotId: "stale" })).includes("wrong-patient")); assert.ok(durableWriteViolations(request({ proposedContent: "", confidence: Number.NaN })).includes("unsupported")); assert.equal(isAllowedDurableMaterial("raw-audio"), false); assert.ok(durableWriteViolations({ ...request(), material: "temporary-transcript" as never }).includes("impermissible-material")); });
test("requires matching attestation membership and fresh timestamp", () => { assert.ok(durableWriteViolations({ ...request(), attestation: undefined }).includes("unattested")); assert.ok(durableWriteViolations({ ...request(), attestation: { ...attestation, draftId: "wrong" as never } }).includes("unattested")); assert.ok(durableWriteViolations({ ...request(), attestation: { ...attestation, approvedCandidateIds: [] } }).includes("attestation-membership")); assert.ok(durableWriteViolations({ ...request(), attestation: { ...attestation, attestedAt: "2025-12-31T23:00:00Z" } }).includes("unattested")); assert.equal(hasValidSupportingSpan(undefined), false); });
test("fails closed for forged source, material, and every discriminator", () => { for (const [key, value] of [["source", "live-ehr"], ["material", "raw-audio"], ["destination", "unknown"], ["statementType", "unknown"], ["changeType", "unknown"], ["speaker", "unknown-speaker"], ["disposition", "unknown"]] as const) { const violations = durableWriteViolations(request({ [key]: value } as never, key === "material" ? { material: "raw-audio" as never } : {})); assert.ok(violations.length > 0, key); } });
test("fails closed for each partial binding mismatch", () => { for (const key of ["sessionId", "patientId", "roundId", "deviceId", "physicianId", "patientSnapshotId", "startedAt", "expiresAt"] as const) assert.equal(isBindingMatch(candidate(), { ...binding, [key]: "forged" } as never), false, key); });
