/**
 * Clinical Alert Types
 * Critical value alerts and clinical decision support
 */

export type AlertSeverity = 'critical' | 'warning' | 'info';
export type AlertCategory = 'lab' | 'vital' | 'medication' | 'clinical' | 'reminder';

export interface ClinicalAlert {
  id: string;
  patientId: string;
  patientName: string;
  category: AlertCategory;
  severity: AlertSeverity;
  title: string;
  message: string;
  value?: string | number;
  normalRange?: string;
  timestamp: string;
  acknowledged: boolean;
  acknowledgedBy?: string;
  acknowledgedAt?: string;
  autoGenerated: boolean;
  source?: string;
}

export interface CriticalLabThreshold {
  labKey: string;
  labName: string;
  criticalLow?: number;
  criticalHigh?: number;
  warningLow?: number;
  warningHigh?: number;
  unit: string;
  enabled: boolean;
}

// Default critical lab thresholds (common ICU values)
export const DEFAULT_CRITICAL_THRESHOLDS: CriticalLabThreshold[] = [
  // Electrolytes
  { labKey: 'na', labName: 'Sodium', criticalLow: 120, criticalHigh: 160, warningLow: 130, warningHigh: 150, unit: 'mEq/L', enabled: true },
  { labKey: 'k', labName: 'Potassium', criticalLow: 2.5, criticalHigh: 6.5, warningLow: 3.0, warningHigh: 5.5, unit: 'mEq/L', enabled: true },
  { labKey: 'ca', labName: 'Calcium', criticalLow: 6.0, criticalHigh: 13.0, warningLow: 7.5, warningHigh: 10.5, unit: 'mg/dL', enabled: true },
  { labKey: 'mg', labName: 'Magnesium', criticalLow: 1.0, criticalHigh: 4.0, warningLow: 1.5, warningHigh: 2.5, unit: 'mg/dL', enabled: true },
  { labKey: 'phos', labName: 'Phosphorus', criticalLow: 1.0, criticalHigh: 8.0, warningLow: 2.0, warningHigh: 5.0, unit: 'mg/dL', enabled: true },

  // Renal
  { labKey: 'cr', labName: 'Creatinine', criticalHigh: 10.0, warningHigh: 4.0, unit: 'mg/dL', enabled: true },
  { labKey: 'bun', labName: 'BUN', criticalHigh: 100, warningHigh: 50, unit: 'mg/dL', enabled: true },

  // Glucose
  { labKey: 'glu', labName: 'Glucose', criticalLow: 40, criticalHigh: 500, warningLow: 60, warningHigh: 300, unit: 'mg/dL', enabled: true },

  // Hematology
  { labKey: 'hgb', labName: 'Hemoglobin', criticalLow: 5.0, criticalHigh: 20.0, warningLow: 7.0, warningHigh: 18.0, unit: 'g/dL', enabled: true },
  { labKey: 'plt', labName: 'Platelets', criticalLow: 20, criticalHigh: 1000, warningLow: 50, warningHigh: 500, unit: 'K/uL', enabled: true },
  { labKey: 'wbc', labName: 'WBC', criticalLow: 1.0, criticalHigh: 50.0, warningLow: 2.0, warningHigh: 20.0, unit: 'K/uL', enabled: true },
  { labKey: 'inr', labName: 'INR', criticalHigh: 5.0, warningHigh: 3.5, unit: '', enabled: true },

  // Blood Gas
  { labKey: 'ph', labName: 'pH', criticalLow: 7.10, criticalHigh: 7.60, warningLow: 7.25, warningHigh: 7.55, unit: '', enabled: true },
  { labKey: 'pco2', labName: 'pCO2', criticalLow: 20, criticalHigh: 70, warningLow: 30, warningHigh: 55, unit: 'mmHg', enabled: true },
  { labKey: 'po2', labName: 'pO2', criticalLow: 40, warningLow: 60, unit: 'mmHg', enabled: true },
  { labKey: 'lactate', labName: 'Lactate', criticalHigh: 8.0, warningHigh: 4.0, unit: 'mmol/L', enabled: true },

  // Cardiac
  { labKey: 'troponin', labName: 'Troponin', criticalHigh: 1.0, warningHigh: 0.04, unit: 'ng/mL', enabled: true },
  { labKey: 'bnp', labName: 'BNP', criticalHigh: 1000, warningHigh: 400, unit: 'pg/mL', enabled: true },
];

// Vital sign thresholds
export interface VitalThreshold {
  vitalKey: string;
  vitalName: string;
  criticalLow?: number;
  criticalHigh?: number;
  warningLow?: number;
  warningHigh?: number;
  unit: string;
  enabled: boolean;
}

export const DEFAULT_VITAL_THRESHOLDS: VitalThreshold[] = [
  { vitalKey: 'hr', vitalName: 'Heart Rate', criticalLow: 40, criticalHigh: 150, warningLow: 50, warningHigh: 120, unit: 'bpm', enabled: true },
  { vitalKey: 'sbp', vitalName: 'Systolic BP', criticalLow: 70, criticalHigh: 200, warningLow: 90, warningHigh: 180, unit: 'mmHg', enabled: true },
  { vitalKey: 'dbp', vitalName: 'Diastolic BP', criticalLow: 40, criticalHigh: 120, warningLow: 50, warningHigh: 100, unit: 'mmHg', enabled: true },
  { vitalKey: 'map', vitalName: 'MAP', criticalLow: 55, criticalHigh: 130, warningLow: 65, warningHigh: 110, unit: 'mmHg', enabled: true },
  { vitalKey: 'rr', vitalName: 'Resp Rate', criticalLow: 8, criticalHigh: 40, warningLow: 10, warningHigh: 30, unit: '/min', enabled: true },
  { vitalKey: 'spo2', vitalName: 'SpO2', criticalLow: 85, warningLow: 92, unit: '%', enabled: true },
  { vitalKey: 'temp', vitalName: 'Temperature', criticalLow: 34.0, criticalHigh: 41.0, warningLow: 36.0, warningHigh: 38.5, unit: '°C', enabled: true },
];

// Helper functions
export const checkLabCritical = (
  labKey: string,
  value: number,
  thresholds: CriticalLabThreshold[] = DEFAULT_CRITICAL_THRESHOLDS
): { severity: AlertSeverity | null; message: string } => {
  const threshold = thresholds.find(t => t.labKey === labKey && t.enabled);
  if (!threshold) return { severity: null, message: '' };

  if (threshold.criticalLow !== undefined && value < threshold.criticalLow) {
    return { severity: 'critical', message: `Critically low ${threshold.labName}: ${value} ${threshold.unit} (< ${threshold.criticalLow})` };
  }
  if (threshold.criticalHigh !== undefined && value > threshold.criticalHigh) {
    return { severity: 'critical', message: `Critically high ${threshold.labName}: ${value} ${threshold.unit} (> ${threshold.criticalHigh})` };
  }
  if (threshold.warningLow !== undefined && value < threshold.warningLow) {
    return { severity: 'warning', message: `Low ${threshold.labName}: ${value} ${threshold.unit} (< ${threshold.warningLow})` };
  }
  if (threshold.warningHigh !== undefined && value > threshold.warningHigh) {
    return { severity: 'warning', message: `High ${threshold.labName}: ${value} ${threshold.unit} (> ${threshold.warningHigh})` };
  }

  return { severity: null, message: '' };
};

export const checkVitalCritical = (
  vitalKey: string,
  value: number,
  thresholds: VitalThreshold[] = DEFAULT_VITAL_THRESHOLDS
): { severity: AlertSeverity | null; message: string } => {
  const threshold = thresholds.find(t => t.vitalKey === vitalKey && t.enabled);
  if (!threshold) return { severity: null, message: '' };

  if (threshold.criticalLow !== undefined && value < threshold.criticalLow) {
    return { severity: 'critical', message: `Critical ${threshold.vitalName}: ${value} ${threshold.unit}` };
  }
  if (threshold.criticalHigh !== undefined && value > threshold.criticalHigh) {
    return { severity: 'critical', message: `Critical ${threshold.vitalName}: ${value} ${threshold.unit}` };
  }
  if (threshold.warningLow !== undefined && value < threshold.warningLow) {
    return { severity: 'warning', message: `Abnormal ${threshold.vitalName}: ${value} ${threshold.unit}` };
  }
  if (threshold.warningHigh !== undefined && value > threshold.warningHigh) {
    return { severity: 'warning', message: `Abnormal ${threshold.vitalName}: ${value} ${threshold.unit}` };
  }

  return { severity: null, message: '' };
};

// Generate alerts from patient data
export const generateAlertsFromLabs = (
  patientId: string,
  patientName: string,
  labText: string,
  thresholds: CriticalLabThreshold[] = DEFAULT_CRITICAL_THRESHOLDS
): ClinicalAlert[] => {
  const alerts: ClinicalAlert[] = [];
  const normalizedText = labText.toLowerCase();

  for (const threshold of thresholds) {
    if (!threshold.enabled) continue;

    // Simple pattern matching for lab values
    const patterns = [
      new RegExp(`${threshold.labKey}[:\\s]+([\\d.]+)`, 'i'),
      new RegExp(`${threshold.labName}[:\\s]+([\\d.]+)`, 'i'),
    ];

    for (const pattern of patterns) {
      const match = normalizedText.match(pattern);
      if (match && match[1]) {
        const value = parseFloat(match[1]);
        if (!isNaN(value)) {
          const { severity, message } = checkLabCritical(threshold.labKey, value, thresholds);
          if (severity) {
            alerts.push({
              id: `${patientId}-${threshold.labKey}-${Date.now()}`,
              patientId,
              patientName,
              category: 'lab',
              severity,
              title: `${threshold.labName} Alert`,
              message,
              value,
              normalRange: `${threshold.warningLow || threshold.criticalLow || '-'} - ${threshold.warningHigh || threshold.criticalHigh || '-'} ${threshold.unit}`,
              timestamp: new Date().toISOString(),
              acknowledged: false,
              autoGenerated: true,
              source: 'lab-parser',
            });
            break; // Only one alert per lab type per patient
          }
        }
      }
    }
  }

  return alerts;
};
