// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { apiFetch } from '@/api/apiClient';
import { createSafeStorage } from '@/utils/safeStorage';
import { readUnexpiredCachedSession } from '@/lib/auth/authBootstrap';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "";
const SUPABASE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? import.meta.env.VITE_SUPABASE_ANON_KEY ?? "";

export const hasSupabaseConfig = Boolean(SUPABASE_URL && SUPABASE_KEY);

if (!hasSupabaseConfig) {
  const message = '[Supabase] Missing required environment variables.';
  throw new Error(`${message} Application startup blocked.`);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabaseUrl = SUPABASE_URL;
const resolvedKey = SUPABASE_KEY;
const authStorage = createSafeStorage();
export const supabaseAuthStorageKey = `sb-${new URL(supabaseUrl).hostname.split('.')[0]}-auth-token`;

/** Bounded bootstrap fallback; the auth client remains refresh authority. */
export const readCachedSessionForBootstrap = () =>
  readUnexpiredCachedSession(authStorage, supabaseAuthStorageKey);

export const supabase = createClient<Database>(supabaseUrl, resolvedKey, {
  auth: {
    storage: authStorage,
    storageKey: supabaseAuthStorageKey,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: apiFetch,
  },
});
