// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { apiFetch } from '@/api/apiClient';
import { createSafeStorage } from '@/utils/safeStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? "";

export const hasSupabaseConfig = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

if (!hasSupabaseConfig) {
  console.warn(
    '[App] Missing Supabase environment variables. API calls will be disabled until configured.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const resolvedUrl = hasSupabaseConfig ? SUPABASE_URL : "http://localhost";
const resolvedKey = hasSupabaseConfig ? SUPABASE_PUBLISHABLE_KEY : "invalid-key";

export const supabase = createClient<Database>(resolvedUrl, resolvedKey, {
  auth: {
    storage: createSafeStorage(),
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: apiFetch,
  },
});
